### ISSUE TITLE
Fortune displays too wide and incorrectly formatted

### ISSUE THREAD

**Issue by abendebury** [tanishq-dubey/cowtab#1]
http://imgur.com/a/7eiuv

You can see the scroll bar on the bottom, and the incorrect border on the right on the second line.

**Comment by Brottweiler** [comment]
I can't seem to reproduce it. If I change my window size, the font scales with it. At most I can loose the left and right pipes, but when it changes font size I can see them again. I never seem to get scrollbars, except if the cowsay is too high so I have to scroll down. 

Edit: As I said that, I got one which had a horizontall scrollbar. A large cowsay with art then text saying

```
If you've got the job, 
we've got the frob.
```

**Comment by philj56** [comment]
I get incorrect borders without being too wide on some:
![screenshot 2016-12-24 at 13 32 12](https://cloud.githubusercontent.com/assets/13610623/21467230/ea8503b6-c9dd-11e6-8f9b-b63431721694.png)

**Comment by abendebury** [comment]
@Brottweiler: Did you try specifically the one in the screenshot? It might be that specific fortune causing issues.

**Comment by metarmask** [comment]
The border breaks because the fortune is using tabs, `"\t".length` is one but tabs are rendered as 8 characters. A fix can be found in #3.

**Comment by Brottweiler** [comment]
Especially noticable when using the `tux-big`. It's so big that you cannot ever read the fortune... the text scales, but it needs to not be able to go outside the window I guess.

**Comment by tanishq-dubey** [comment]
The ASCII art is definitely a problem. The fortune files do use a nonstandard tab width, just as metarmask noticed, I think most of the fortune files were normalized to fix this. In addition, the text size is just a CSS fix right (I'm just guessing, might be something else).

**Comment by Brottweiler** [comment]
This is probably not an issue anymore with the new update since the cowsay font seems smaller.

**Comment by tanishq-dubey** [comment]
Yep, tagged and closed. The scaling is now based on vertical viewport height instead of horizontal. Should fix it all. Reopen if you encounter another broken fortune.
