### ISSUE TITLE
Latest Chrome version renders screen black

### ISSUE THREAD

**Issue by alberts-s** [tanishq-dubey/cowtab#12]
Hello,
Upon updating to latest Chrome addon version (1.03) the cowtab screen is [rendered black](https://i.imgur.com/Xf0cxrX.png). There is also the following error in console.

> private.js:38 Uncaught (in promise) TypeError: Illegal invocation: Function must be called on an object of type StorageArea
>     at Promise (private.js:38)
>     at new Promise (<anonymous>)
>     at Proxy.args (private.js:37)
>     at getOptions (newtab.js:14)

Chrome version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by abendebury** [comment]
The extension no longer has configuration options either.

**Comment by ghost** [comment]
Yes, it looks like an update to Chrome in the last few months broke this extension from displaying any cows. Only the fortunes appear. In addition, I also don't see any options in the configuration menu anymore, either.

**Comment by abendebury** [comment]
See my pull request above if you want a local fix for this.
