### ISSUE TITLE
Changing background color does not work as expected

### ISSUE THREAD

**Issue by abendebury** [tanishq-dubey/cowtab#9]
If you change the background color via the settings, only a box of color near the cow gets the new color:

http://imgur.com/38sqBDK

**Comment by abendebury** [comment]
The issue is that the background color is specified on the `html` element by default:

https://github.com/tanishq-dubey/cowtab/blob/master/newtab/newtab.css#L10

But it's updated on the `body` element:

https://github.com/tanishq-dubey/cowtab/blob/master/newtab/newtab.js#L70

**Comment by tanishq-dubey** [comment]
I don't think this occurs any more, so I am closing the issue. If it still occurs, feel free to reopen.
